# Generated by Django 3.1.2 on 2021-01-17 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuado', models.FloatField()),
                ('generoRated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('episodios', models.PositiveIntegerField()),
                ('generos', models.TextField()),
                ('sinopsis', models.TextField()),
                ('puntuacion_usuario', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('puntuacion_BD', models.FloatField()),
                ('nuevo', models.BooleanField()),
                ('ratings', models.ManyToManyField(to='main.Rating')),
            ],
        ),
    ]
